#!/usr/bin/python3
import sys
from math import floor

COLORS = {
        "W" : "white",
        "B" : "black"
        }

def drawBoard():
    svg.write('<rect x="0" y="0" width="380" height="380" fill="#ebcc7b" stroke="transparent"/>')
    svg.write('<rect x="10" y="10" fill="#ebcc7b" stroke="black" stroke-width="2" width="360" height="360"/>')
    for x in range(17):
        svg.write('<line x1="10" x2="370" y1="%d" y2="%d" stroke="black"/>' % (30+(x*20), 30+(x*20)))
        svg.write('<line x1="%d" x2="%d" y1="10" y2="370" stroke="black"/>' % (30+(x*20), 30+(x*20)))

def parseSgf(sgf):
    moves = sgf.read().split(';')[2:]
    out = []
    for move in moves:
        player = COLORS[move[0]]
        x = ord(move[2].lower()) - ord('a')
        y = ord(move[3].lower()) - ord('a')
        out.append((player, x, y))
    return out

def renderToBoard(player, x, y, index):
    svg.write('<circle cx="%d" cy="%d" r="10" stroke="black" fill="%s"/>' % ((x*20)+10, (y*20)+10, player))
    # swap colors for the text
    if player == "white":
        player = "black"
    else:
        player = "white"
    svg.write('<text x="%d" y="%d" font-size="11" font-family="sans-serif"\
 dominant-baseline="middle" text-anchor="middle" stroke="%s"\
 fill="%s">%d</text>\n' % ((x*20)+10, (y*20)+10, player, player, index))

def renderKos(move, index):
    player, number, color, at = move
    x = 10 + (80 * (index % 5))
    y = 400 + (20 * floor(index/5))
    svg.write('<circle cx="%d" cy="%d" r="10" stroke="black" fill="%s"/>' % (x, y, player))
    c = "white"
    if player == "white":
        c = "black"
    svg.write('<text x="%d" y="%d" font-size="11" font-family="sans-serif"\
 dominant-baseline="middle" text-anchor="middle" stroke="%s"\
 fill="%s">%d</text>' % (x, y, c, c, number))
    svg.write('<text x="%d" y="%d" font-size="11" font-family="sans-serif"\
 dominant-baseline="middle" text-anchor="middle">at</text>' % (x+20, y))
    svg.write('<circle cx="%d" cy="%d" r="10" stroke="black" fill="%s"/>' % (x+40, y, color))
    c = "white"
    if color == "white":
        c = "black"
    svg.write('<text x="%d" y="%d" font-size="11" font-family="sans-serif"\
 dominant-baseline="middle" text-anchor="middle" stroke="%s"\
 fill="%s">%d</text>\n' % (x+40, y, c, c, at+1))

def parseMove(move, index, kos):
    player, x, y = move
    if (("black", x, y) in kifu[0:index-1]):
        kos.append((player, index, "black", kifu.index(("black", x, y))))
    elif (("white", x, y) in kifu[0:index-1]):
        kos.append((player, index, "white", kifu.index(("white", x, y))))
    else:
        renderToBoard(player, x, y, index)

if __name__ == "__main__":
    with open(sys.argv[2], 'w') as svg:
        with open(sys.argv[1], 'r') as sgf:
            svg.write('<svg width="380" height="500" xmlns="http://www.w3.org/2000/svg">\n')
            drawBoard()
            played = []
            kifu = parseSgf(sgf)
            kos = []
            for index, move in enumerate(kifu):
                parseMove(move, index + 1, kos)
            for index, move in enumerate(kos):
                renderKos(move, index)
            svg.write('</svg>')
